### ISSUE TITLE
cannot create /init/initdb.sql: Permission denied

### ISSUE THREAD

**Issue by phatpaul** [reisbel/guacamole-docker-compose#6]
guacamole-init-guacamole-db-1  | /bin/sh: 1: cannot create /init/initdb.sql: Permission denied

I tried adding :rw to the volume, but no luck:

```
version: "3"
services:

  init-guacamole-db:
    image: guacamole/guacamole:latest
    command: ["/bin/sh", "-c", "test -e /init/initdb.sql && echo 'init file already exists' || /opt/guacamole/bin/initdb.sh --postgres > /init/initdb.sql" ]
    volumes:
      - dbinit:/init:rw
```

**Comment by phatpaul** [comment]
FYI I got around it by adding `user: 0:0` to docker-compose.  Not sure it's the best approach, but it worked.
```
version: "3"
services:

  init-guacamole-db:
    image: guacamole/guacamole:latest
    user: 0:0
    command: ["/bin/sh", "-c", "test -e /init/initdb.sql && echo 'init file already exists' || /opt/guacamole/bin/initdb.sh --postgres > /init/initdb.sql" ]
    volumes:
      - dbinit:/init:z
```
